version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: moodjournal_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: moodjournal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d

  etl:
    build:
      context: .
      dockerfile: ./etl/Dockerfile
    container_name: moodjournal_etl
    depends_on:
    - postgres

volumes:
  postgres_data:

